-- ============================================================================
-- schema.sql
-- NSE Scanner Database Schema
-- PostgreSQL 15+
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================================
-- MASTER STOCK LIST
-- ============================================================================

CREATE TABLE stocks (
    symbol              TEXT PRIMARY KEY,
    company_name        TEXT,
    exchange            TEXT NOT NULL DEFAULT 'NSE',
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_stocks_active
ON stocks(is_active);

-- ============================================================================
-- DAILY OHLC DATA
-- Raw candles downloaded from Yahoo Finance
-- ============================================================================

CREATE TABLE daily_candles (
    symbol              TEXT NOT NULL REFERENCES stocks(symbol) ON DELETE CASCADE,

    candle_date         DATE NOT NULL,

    open                DOUBLE PRECISION NOT NULL,
    high                DOUBLE PRECISION NOT NULL,
    low                 DOUBLE PRECISION NOT NULL,
    close               DOUBLE PRECISION NOT NULL,
    volume              BIGINT NOT NULL,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY(symbol, candle_date)
);

CREATE INDEX idx_daily_symbol
ON daily_candles(symbol);

CREATE INDEX idx_daily_date
ON daily_candles(candle_date DESC);

-- ============================================================================
-- LAST BUY SIGNAL
--
-- Stores ONLY the latest BUY signal generated by the UT Bot.
-- This avoids scanning historical data every day.
-- ============================================================================

CREATE TABLE latest_buy_signal (

    symbol                  TEXT PRIMARY KEY
                            REFERENCES stocks(symbol)
                            ON DELETE CASCADE,

    signal_date             DATE NOT NULL,

    signal_open             DOUBLE PRECISION NOT NULL,
    signal_high             DOUBLE PRECISION NOT NULL,
    signal_low              DOUBLE PRECISION NOT NULL,
    signal_close            DOUBLE PRECISION NOT NULL,

    today_close             DOUBLE PRECISION,

    breakout                BOOLEAN NOT NULL DEFAULT FALSE,

    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_breakout
ON latest_buy_signal(breakout);

-- ============================================================================
-- DAILY SCAN RESULTS
--
-- Keeps history of every scan.
-- ============================================================================

CREATE TABLE scan_results (

    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    scan_date               DATE NOT NULL,

    symbol                  TEXT NOT NULL
                            REFERENCES stocks(symbol)
                            ON DELETE CASCADE,

    -- UT Bot signal for this row: BUY / SELL / NONE
    signal                  TEXT NOT NULL DEFAULT 'NONE',

    buy_signal_date         DATE,          -- NULL when signal != BUY

    buy_high                DOUBLE PRECISION NOT NULL DEFAULT 0,

    today_close             DOUBLE PRECISION NOT NULL,

    breakout                BOOLEAN NOT NULL DEFAULT FALSE,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(scan_date, symbol)
);

CREATE INDEX idx_scan_date
ON scan_results(scan_date DESC);

CREATE INDEX idx_scan_symbol
ON scan_results(symbol);

-- ============================================================================
-- VIEW
-- ============================================================================

CREATE VIEW latest_breakouts AS
SELECT
    s.symbol,
    s.company_name,
    l.signal_date,
    l.signal_high,
    l.today_close,
    l.breakout,
    l.updated_at
FROM latest_buy_signal l
JOIN stocks s
ON s.symbol = l.symbol
WHERE l.breakout = TRUE;

-- ============================================================================
-- VIEW: today's BUY / SELL signals
-- ============================================================================

CREATE VIEW todays_signals AS
SELECT
    r.scan_date,
    r.symbol,
    s.company_name,
    r.signal,
    r.buy_signal_date,
    r.today_close,
    r.buy_high,
    r.breakout
FROM scan_results r
JOIN stocks s ON s.symbol = r.symbol
WHERE r.scan_date = CURRENT_DATE
  AND r.signal IN ('BUY', 'SELL')
ORDER BY r.signal, r.symbol;

-- ============================================================================
-- MIGRATION (run on existing databases)
-- If applying to a DB that already has scan_results without the signal column:
--
--   ALTER TABLE scan_results
--       ADD COLUMN IF NOT EXISTS signal TEXT NOT NULL DEFAULT 'NONE',
--       ALTER COLUMN buy_signal_date DROP NOT NULL,
--       ALTER COLUMN buy_high SET DEFAULT 0,
--       ALTER COLUMN breakout SET DEFAULT FALSE;
--
-- ============================================================================