-- ============================================================================
-- schema.sql
-- NSE Scanner Database Schema
-- PostgreSQL 15+
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================================
-- MASTER STOCK LIST
-- ============================================================================

CREATE TABLE stocks (
    symbol              TEXT PRIMARY KEY,
    company_name        TEXT,
    exchange            TEXT NOT NULL DEFAULT 'NSE',
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_stocks_active
ON stocks(is_active);

-- ============================================================================
-- DAILY OHLC DATA
-- Raw candles downloaded from Yahoo Finance
-- ============================================================================

CREATE TABLE daily_candles (
    symbol              TEXT NOT NULL REFERENCES stocks(symbol) ON DELETE CASCADE,

    candle_date         DATE NOT NULL,

    open                DOUBLE PRECISION NOT NULL,
    high                DOUBLE PRECISION NOT NULL,
    low                 DOUBLE PRECISION NOT NULL,
    close               DOUBLE PRECISION NOT NULL,
    volume              BIGINT NOT NULL,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY(symbol, candle_date)
);

CREATE INDEX idx_daily_symbol
ON daily_candles(symbol);

CREATE INDEX idx_daily_date
ON daily_candles(candle_date DESC);

-- ============================================================================
-- LAST BUY SIGNAL
--
-- Stores ONLY the latest BUY signal generated by the UT Bot per symbol.
-- Used as a fast lookup by the breakout engine.
-- ============================================================================

CREATE TABLE latest_buy_signal (

    symbol                  TEXT PRIMARY KEY
                            REFERENCES stocks(symbol)
                            ON DELETE CASCADE,

    signal_date             DATE NOT NULL,

    signal_open             DOUBLE PRECISION NOT NULL,
    signal_high             DOUBLE PRECISION NOT NULL,
    signal_low              DOUBLE PRECISION NOT NULL,
    signal_close            DOUBLE PRECISION NOT NULL,

    today_close             DOUBLE PRECISION,

    breakout                BOOLEAN NOT NULL DEFAULT FALSE,

    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_breakout
ON latest_buy_signal(breakout);

-- ============================================================================
-- DAILY SCAN RESULTS
--
-- Keeps history of every scan.
-- ============================================================================

CREATE TABLE scan_results (

    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    scan_date               DATE NOT NULL,

    symbol                  TEXT NOT NULL
                            REFERENCES stocks(symbol)
                            ON DELETE CASCADE,

    -- UT Bot signal for this row: BUY / SELL / NONE
    signal                  TEXT NOT NULL DEFAULT 'NONE',

    buy_signal_date         DATE,          -- NULL when signal != BUY

    buy_high                DOUBLE PRECISION NOT NULL DEFAULT 0,

    today_close             DOUBLE PRECISION NOT NULL,

    breakout                BOOLEAN NOT NULL DEFAULT FALSE,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(scan_date, symbol)
);

CREATE INDEX idx_scan_date
ON scan_results(scan_date DESC);

CREATE INDEX idx_scan_symbol
ON scan_results(symbol);

-- ============================================================================
-- BUY WATCH LIST
--
-- All stocks that currently have a BUY signal from the UT Bot.
-- Unique per (symbol, signal_date) — no duplicates for the same signal event.
-- Populated/refreshed by the scanner on every run.
-- Entries are removed when a SELL signal is generated for that symbol.
-- ============================================================================

CREATE TABLE buy_watch_list (

    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    symbol                  TEXT NOT NULL
                            REFERENCES stocks(symbol)
                            ON DELETE CASCADE,

    signal_date             DATE NOT NULL,       -- date the BUY signal fired

    -- Heikin Ashi OHLC of the BUY signal candle (used for breakout comparison)
    ha_open                 DOUBLE PRECISION NOT NULL,
    ha_high                 DOUBLE PRECISION NOT NULL,
    ha_low                  DOUBLE PRECISION NOT NULL,
    ha_close                DOUBLE PRECISION NOT NULL,

    trailing_stop           DOUBLE PRECISION NOT NULL,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- One entry per symbol per signal event
    UNIQUE(symbol, signal_date)
);

CREATE INDEX idx_buy_watch_symbol
ON buy_watch_list(symbol);

CREATE INDEX idx_buy_watch_date
ON buy_watch_list(signal_date DESC);

-- ============================================================================
-- CONFIRMED BREAKOUTS
--
-- Stocks from buy_watch_list where today's HA close > buy signal candle HA high.
-- Updated daily by the breakout engine.
-- One row per symbol (latest confirmation wins via upsert).
-- ============================================================================

CREATE TABLE confirmed_breakouts (

    symbol                  TEXT PRIMARY KEY
                            REFERENCES stocks(symbol)
                            ON DELETE CASCADE,

    signal_date             DATE NOT NULL,       -- date of the original BUY signal

    buy_candle_open         DOUBLE PRECISION NOT NULL,
    buy_candle_high         DOUBLE PRECISION NOT NULL,
    buy_candle_low          DOUBLE PRECISION NOT NULL,
    buy_candle_close        DOUBLE PRECISION NOT NULL,
    buy_candle_range_pct    DOUBLE PRECISION NOT NULL,   -- (high-low)/low * 100

    confirmation_date       DATE NOT NULL,       -- date today's close crossed buy high
    confirmed_close         DOUBLE PRECISION NOT NULL,   -- HA close that triggered confirmation

    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_confirmed_date
ON confirmed_breakouts(confirmation_date DESC);

-- ============================================================================
-- VIEW: today's BUY / SELL signals (most recent scan session)
-- ============================================================================

CREATE OR REPLACE VIEW todays_signals AS
SELECT
    r.scan_date,
    r.symbol,
    s.company_name,
    r.signal,
    r.buy_signal_date,
    r.today_close,
    r.buy_high,
    r.breakout
FROM scan_results r
JOIN stocks s ON s.symbol = r.symbol
WHERE r.scan_date = (SELECT MAX(scan_date) FROM scan_results WHERE signal IN ('BUY', 'SELL'))
  AND r.signal IN ('BUY', 'SELL')
ORDER BY r.signal, r.symbol;

-- ============================================================================
-- VIEW: current confirmed breakout watch list with company names
-- ============================================================================

CREATE OR REPLACE VIEW confirmed_breakouts_view AS
SELECT
    c.symbol,
    s.company_name,
    c.signal_date,
    c.buy_candle_high,
    c.buy_candle_range_pct,
    c.confirmation_date,
    c.confirmed_close,
    ROUND(((c.confirmed_close - c.buy_candle_high) / c.buy_candle_high * 100)::NUMERIC, 2) AS pct_above_buy_high,
    c.updated_at
FROM confirmed_breakouts c
JOIN stocks s ON s.symbol = c.symbol
ORDER BY c.confirmation_date DESC, c.symbol;

-- ============================================================================
-- CRUDE OIL MINI (5-MIN CANDLES + STRATEGY + OI + PCR)
-- ============================================================================

CREATE TABLE IF NOT EXISTS crude_oil_data (
    timestamp               TIMESTAMPTZ PRIMARY KEY,
    symbol                  TEXT NOT NULL DEFAULT 'CRUDEOILM',
    instrument_key          TEXT NOT NULL,
    open                    DOUBLE PRECISION NOT NULL,
    high                    DOUBLE PRECISION NOT NULL,
    low                     DOUBLE PRECISION NOT NULL,
    close                   DOUBLE PRECISION NOT NULL,
    volume                  BIGINT NOT NULL,
    open_interest           BIGINT NOT NULL DEFAULT 0,
    pcr                     DOUBLE PRECISION,
    ha_open                 DOUBLE PRECISION,
    ha_high                 DOUBLE PRECISION,
    ha_low                  DOUBLE PRECISION,
    ha_close                DOUBLE PRECISION,
    atr                     DOUBLE PRECISION,
    trailing_stop           DOUBLE PRECISION,
    signal                  TEXT NOT NULL DEFAULT 'NONE',  -- 'BUY', 'SELL', 'NONE'
    buy_confirmed           BOOLEAN NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crude_oil_timestamp ON crude_oil_data(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_crude_oil_signal ON crude_oil_data(signal);
CREATE INDEX IF NOT EXISTS idx_crude_oil_confirmed ON crude_oil_data(buy_confirmed);

-- ============================================================================
-- MIGRATION (run on existing databases — safe to ignore on fresh installs)
-- ============================================================================
--
-- ALTER TABLE scan_results
--     ADD COLUMN IF NOT EXISTS signal TEXT NOT NULL DEFAULT 'NONE',
--     ALTER COLUMN buy_signal_date DROP NOT NULL,
--     ALTER COLUMN buy_high SET DEFAULT 0,
--     ALTER COLUMN breakout SET DEFAULT FALSE;
--